apiVersion: apps/v1
kind: Deployment
metadata:
        name: jj-deployment
        labels:
                app: jj
spec:           
        replicas: 3
        selector:
                matchLabels:
                        app: jj
        template:       
                metadata:
                        labels:
                                app: jj
                spec:   
                        containers:
                                - name: mytom
                                  image: aisshwarya16/mytom:1.0
                                  ports:
                                        - containerPort: 8080
